wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.2
    t:
      1:
      - 3
      4: 3.8.2
      5: 0.10.21
      8:
      - 1
      - 5
